# -*- coding: utf-8 -*-
"""target_bank.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/to-nakanishi/bank-marketing-analysis/blob/main/target_bank.ipynb
"""

import pandas as pd
import numpy as np

#1-1 読込、表示

from google.colab import drive
drive.mount('/content/drive')

testpath='/content/drive/MyDrive/Colab Notebooks/signate/bank_target/test.csv'
trainpath='/content/drive/MyDrive/Colab Notebooks/signate/bank_target/train.csv'
samplepath='/content/drive/MyDrive/Colab Notebooks/signate/bank_target/submit_sample.csv'
testdata=pd.read_csv(testpath)
traindata=pd.read_csv(trainpath)
sampledata=pd.read_csv(samplepath)

print(traindata.columns.tolist())
print(f"\n合計カラム数: {len(traindata.columns)}")
print("\n\nトレイン\n",traindata.head(10))
print(traindata.tail(10))

"""下処理（変換）

グループ層化:age,balance,day,duration  
数値化（リスト）:job,education,contact,poutcome  
数値化（0，1):marital,default,housing,loan  
数値化（その他):month,pdays  



"""

#1-2　欠損値の確認

print("--- NaNの数 ---")
print(traindata.isnull().sum())

print("\n--- 'unknown' の数 ---")
cat_cols = traindata.select_dtypes(include='object').columns
for col in cat_cols:
    unknown_count = (traindata[col] == 'unknown').sum()
    print(f"{col}: {unknown_count}")

cat_cols = traindata.select_dtypes(include='object').columns

unknown_stats = []
for col in cat_cols:
    count = (traindata[col] == 'unknown').sum()
    ratio = count / len(traindata) * 100
    unknown_stats.append([col, count, f"{ratio:.2f}%"])

unknown_df = pd.DataFrame(unknown_stats, columns=['Column', 'Unknown Count', 'Percentage'])
print(unknown_df)

"""欠損値なし  
UNKNOWNの処理については要検討
"""

print(traindata[traindata["job"] == "unknown"].head(20))

print("\n\n",traindata[traindata["education"] == "unknown"].head())
target_data = traindata[(traindata["age"] < 15) & (traindata["education"] == "unknown")]
target_data

"""job：残高やその他属性から推測困難のため補完せず  
educationの15歳未満にUNKNOWNはいないため補完不要  
contact、poutcome　補完不要  
"""

#2-1　下処理　グループ層の可視化
import matplotlib.pyplot as plt
import seaborn as sns

cols = ['age', 'balance', 'day', 'duration']

# グラフの表示エリアを作成
plt.figure(figsize=(15, 10))

for i, col in enumerate(cols):
    plt.subplot(2, 2, i+1)
    # ヒストグラムを表示
    sns.histplot(traindata[col], bins=30, kde=True)
    plt.title(f'Distribution of {col}')

plt.tight_layout()
plt.show()

"""ヒストグラムの分布より層化は以下のとおり行う。    
１年齢　20未満：0、20代：1、30～50：2、51～60：3  
２日付　５日区切りで順に1,2,3,4,5,6(31日含む)  
３残高と通話時間　対数変換  
"""

#2-2　下処理(グループ化:age,balance,day,duration)

def age_binning(x):
    if x < 20:return 0
    elif x < 30:return 1
    elif x < 50:return 2
    elif x < 60:return 3
    else:return 4

def day_binning(x):
    if x <= 5: return 0
    elif x <= 10: return 1
    elif x <= 15: return 2
    elif x <= 20: return 3
    elif x <= 25: return 4
    else: return 5

for df in [traindata, testdata]:
    df['age_bin'] = df['age'].apply(age_binning)
    df['day_bin'] = df['day'].apply(day_binning)

all_min = min(traindata['balance'].min(), testdata['balance'].min())
for df in [traindata, testdata]:
    if all_min < 0:
        df['balance_log'] = np.log1p(df['balance'] - all_min)
    else:
        df['balance_log'] = np.log1p(df['balance'])
    df['duration_log'] = np.log1p(df['duration'])

print("--- traindataの準備完了 ---")
print(traindata[['age_bin', 'day_bin', 'balance_log', 'duration_log']].head())

print("\n--- testdataの準備完了 ---")
print(testdata[['age_bin', 'day_bin', 'balance_log', 'duration_log']].head())

#2-3　下処理　数値化（リスト）:marital,job,education,contact,poutcome

from sklearn.preprocessing import LabelEncoder

cat_cols = ['marital','job', 'education', 'contact', 'poutcome']

for col in cat_cols:
    le = LabelEncoder()
    le.fit(pd.concat([traindata[col], testdata[col]]))

    traindata[col] = le.transform(traindata[col])
    testdata[col] = le.transform(testdata[col])

print(traindata[cat_cols].head())

#2-4　下処理　数値化（0，1):default,housing,loan

binary_map = {'yes': 1, 'no': 0}

for df in [traindata, testdata]:
    df['default'] = df['default'].map(binary_map)
    df['housing'] = df['housing'].map(binary_map)
    df['loan'] = df['loan'].map(binary_map)

print(traindata[[ 'default', 'housing', 'loan']].head())

#2-5　下処理　数値化（その他):month,pdays

month_map = {
    'jan': 1, 'feb': 2, 'mar': 3, 'apr': 4, 'may': 5, 'jun': 6,
    'jul': 7, 'aug': 8, 'sep': 9, 'oct': 10, 'nov': 11, 'dec': 12
}
for df in [traindata, testdata]:
    if df['month'].dtype == 'object':
        df['month'] = df['month'].map(month_map)

plt.figure(figsize=(5, 3))
sns.histplot(traindata['pdays'], bins=50, kde=True)
plt.title('Distribution of pdays')
plt.xlabel('Days passed after previous contact')
plt.ylabel('Count')
plt.show()

"""pdays
-1，0，1～200，201～400，401～でグループ化
"""

def pdays_binning(x):
    if x == -1: return 0
    elif x == 0: return 1
    elif x <= 200: return 2
    elif x <= 400: return 3
    else: return 4

for df in [traindata, testdata]:
    df['pdays_bin'] = df['pdays'].apply(pdays_binning)

print("pdaysのグループ化が完了しました！")
print(traindata['pdays_bin'].value_counts().sort_index())

#3-1　学習モデル構築（AUC）
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

features = [
    'age_bin', 'job', 'marital', 'education', 'default',
    'balance_log', 'housing', 'loan', 'contact', 'day_bin',
    'month', 'duration_log', 'campaign', 'pdays_bin', 'previous', 'poutcome'
]

X = traindata[features]
y = traindata['y']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

train_set = lgb.Dataset(X_train, label=y_train)
val_set = lgb.Dataset(X_val, label=y_val, reference=train_set)

params = {
    'objective': 'binary',    # 0か1かを当てる
    'metric': 'auc',          # 精度を測る指標（AUC）
    'verbosity': -1,
    'boosting_type': 'gbdt',
}

model = lgb.train(
    params,
    train_set,
    valid_sets=[train_set, val_set],
    num_boost_round=1000,
    callbacks=[lgb.early_stopping(stopping_rounds=100)]
)

y_pred = model.predict(X_val)
score = roc_auc_score(y_val, y_pred)
print(f"検証データのAUCスコア: {score:.4f}")

#3-2　学習モデル構築（ランダムフォレスト）
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict_proba(X_val)[:, 1]

rf_score = roc_auc_score(y_val, y_pred_rf)
print(f"ランダムフォレストのAUCスコア: {rf_score:.4f}")

#3-3　学習モデル構築（XGBoost）
import xgboost as xgb

dtrain = xgb.DMatrix(X_train, label=y_train)
dval = xgb.DMatrix(X_val, label=y_val)

params_xgb = {
    'objective': 'binary:logistic',
    'eval_metric': 'auc',
    'eta': 0.1,
}

xgb_model = xgb.train(
    params_xgb,
    dtrain,
    num_boost_round=1000,
    evals=[(dtrain, 'train'), (dval, 'val')],
    early_stopping_rounds=100,
    verbose_eval=50
)

y_pred_xgb = xgb_model.predict(dval)
print(f"XGBoostのAUC: {roc_auc_score(y_val, y_pred_xgb):.4f}")

#3-4　学習モデル構築（ロジスティック回帰）
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

lr_model = LogisticRegression()
lr_model.fit(X_train_scaled, y_train)

y_pred_lr = lr_model.predict_proba(X_val_scaled)[:, 1]
print(f"ロジスティック回帰のAUC: {roc_auc_score(y_val, y_pred_lr):.4f}")

#3-5　学習モデル構築（アンサンブル）

final_blend = (
    y_pred * 0.4 +
    y_pred_xgb * 0.3 +
    y_pred_rf * 0.2 +
    y_pred_lr * 0.1
)

blend_score = roc_auc_score(y_val, final_blend)
print(f"4種盛りアンサンブルのAUCスコア: {blend_score:.4f}")

#4　寄与度の確認

# 1. 各モデルの重要度を抽出
fi_lgb = pd.DataFrame({'feature': features, 'importance': model.feature_importance(importance_type='gain'), 'model': 'LightGBM'})
fi_xgb = pd.DataFrame({'feature': features, 'importance': list(xgb_model.get_score(importance_type='gain').values()), 'model': 'XGBoost'})
fi_rf = pd.DataFrame({'feature': features, 'importance': rf_model.feature_importances_, 'model': 'RandomForest'})

# 2. 比較のために正規化（合計を1にする）
for df in [fi_lgb, fi_xgb, fi_rf]:
    df['importance'] = df['importance'] / df['importance'].sum()

# 3. グラフ表示
plt.figure(figsize=(10, 6))
combined_fi = pd.concat([fi_lgb, fi_rf]) # 今回は代表してLGBMとRFを比較
sns.barplot(x='importance', y='feature', hue='model', data=combined_fi)
plt.title('Feature Importance Comparison')
plt.show()

"""修正事項  
duration_logは寄与度が0.4と最も高いが因果が逆になっているため要削除  
（成約したから説明等で長いのであって、電話時間を無理に伸ばすように改  
善しても成約率の上昇にはつながらないと想定されるため）
"""

#5-1　学習モデル（AUC)　duration_log抜き
features_no_duration = [f for f in features if 'duration' not in f]

X_train_nd = X_train[features_no_duration]
X_val_nd = X_val[features_no_duration]

model_nd = lgb.train(
    params,
    lgb.Dataset(X_train_nd, label=y_train),
    num_boost_round=1000,
    valid_sets=[lgb.Dataset(X_val_nd, label=y_val)],
    callbacks=[lgb.early_stopping(stopping_rounds=100)]
)

y_pred_nd = model_nd.predict(X_val_nd)
print(f"duration抜きのAUCスコア: {roc_auc_score(y_val, y_pred_nd):.4f}")

#5-2　学習モデル（ランダムフォレスト)　duration_log抜き

from sklearn.ensemble import RandomForestClassifier

rf_model_nd = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)

rf_model_nd.fit(X_train_nd, y_train)

y_pred_rf_nd = rf_model_nd.predict_proba(X_val_nd)[:, 1]
rf_auc_nd = roc_auc_score(y_val, y_pred_rf_nd)

print(f"RandomForest(duration抜き)のAUCスコア: {rf_auc_nd:.4f}")

#6　寄与度の確認

# 1. 各モデルの重要度を抽出
fi_lgb_nd = pd.DataFrame({
    'feature': features_no_duration,
    'importance': model_nd.feature_importance(importance_type='gain'),
    'model': 'LightGBM'
})

fi_rf_nd = pd.DataFrame({
    'feature': features_no_duration,
    'importance': rf_model_nd.feature_importances_,
    'model': 'RandomForest'
})

# 2. 正規化（合計を1にして比較しやすくする）
for df in [fi_lgb_nd, fi_rf_nd]:
    df['importance'] = df['importance'] / df['importance'].sum()

# 3. グラフ表示
plt.figure(figsize=(12, 10))
combined_fi_nd = pd.concat([fi_lgb_nd, fi_rf_nd])

# 重要度の高い順に並び替えて表示
order = fi_lgb_nd.sort_values('importance', ascending=False)['feature']

sns.barplot(x='importance', y='feature', hue='model', data=combined_fi_nd, order=order)
plt.title('Feature Importance Comparison (Without Duration)')
plt.grid(axis='x', linestyle='--', alpha=0.5)
plt.show()

# 7 テストデータ duration を除外
X_test_nd = testdata[features_no_duration]
test_pred_nd = model_nd.predict(X_test_nd)

# 8　提出csv作成

submission = pd.DataFrame({
    'id': testdata['id'],
    'y': test_pred_nd
})
submission.to_csv('submission_no_duration.csv', index=False, header=False)

print("提出用ファイル 'submission_no_duration.csv' が作成されました！")
